# Workflow utilizado para desplegar una aplicaci칩n en una M치quina Virtual.

name: CD - Despliegue en M치quina Virtual. 


on:
  workflow_run:
    workflows: ["Java CI with Maven"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        run: echo "Desplegando aplicaci칩n..."