# Workflow utilizado para desplegar una aplicaci칩n en una M치quina Virtual.

name: CD - Despliegue en M치quina Virtual. 


on:
  workflow_run:
    workflows: ["Java CI with Maven"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Imprimir informaci칩n deploy
        run: |
          echo "Hola."
          echo "Usuario Docker: ${{ secrets.DOCKER_USERNAME }}"
          echo "IP instancia EC2: ${{ vars.IP_EC2_CDCI }}"
